name: Code Change Analysis

on:
  push:
    branches: [ main, master, dev ]  # Customize branches as needed

jobs:
  analyze-code-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch complete history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install GitPython tree_sitter
        # Install language parsers for tree-sitter
        pip install tree-sitter-python tree-sitter-javascript tree-sitter-typescript tree-sitter-java tree-sitter-go tree-sitter-rust

    - name: Analyze code changes
      run: |
        python .github/scripts/analyze_code_changes.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Store analysis results
      uses: actions/upload-artifact@v3
      with:
        name: code-analysis
        path: .docai/